# ScheduledTask.ps1
# Creates a daily scheduled task that generates a system report.
# This is a plain PowerShell script (not DSC) to exercise the ScriptAnalysisService path.

$taskName   = 'X2A-DailyReport'
$scriptPath = 'C:\dsc-configs\configs\app-deployment\scripts\daily-report.ps1'
$reportDir  = 'C:\x2a-reports'

# -- Create report output directory ------------------------------------------

if (-not (Test-Path $reportDir)) {
    New-Item -Path $reportDir -ItemType Directory -Force | Out-Null
    Write-Host "[ScheduledTask] Created report directory: $reportDir"
}

# -- Remove existing task if present -----------------------------------------

$existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if ($existing) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    Write-Host "[ScheduledTask] Removed existing task: $taskName"
}

# -- Create scheduled task ---------------------------------------------------

$action  = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$scriptPath`""

$trigger = New-ScheduledTaskTrigger -Daily -At '06:00AM'

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable

Register-ScheduledTask `
    -TaskName    $taskName `
    -Action      $action `
    -Trigger     $trigger `
    -Settings    $settings `
    -Description 'Daily system report generated by x2ansible demo' `
    -User        'SYSTEM' `
    -RunLevel    Highest `
    | Out-Null

Write-Host "[ScheduledTask] Registered task: $taskName (daily at 06:00 AM)"

# -- Run once immediately for verification -----------------------------------

Start-ScheduledTask -TaskName $taskName
Write-Host "[ScheduledTask] Triggered initial run. Reports will be written to $reportDir"
